---

ANACONDA_INSTALL_DIR: C:\Tools\Anaconda3
BOT_DIR:  C:\bot\avt_pro

# Ansible working directory on remote host
working_dir: ""

# IPv4 host address
ansible_port: 
# IPv4 host address
ansible_user: gulaftab
ansible_password: 0)AKkm+y/SS+UO|

#for communicating with windows machines
ansible_connection: winrm
ansible_winrm_transport: ntlm
#ansible_winrm_transport: basic
ansible_winrm_server_cert_validation: ignore
