---
- name: Create remote installation Directory if it does not exists
  win_file:
   path: '{{BOT_INSTALL_DIR}}'
   state: directory 

- name: Copy src to Installs directory
  win_copy:
   src: '{{LOCAL_DATA_DIR}}/Empaxco/'
   dest: '{{BOT_INSTALL_DIR}}'
   remote_src: False
   register: copy_completed
   until: src_folder copy succeeded


- name: Copy chrome driver to remote host
  win_copy:
   src: '{{LOCAL_DATA_DIR}}/driver'
   dest: '{{BOT_INSTALL_DIR}}'
   remote_src: False
 
- name: Replace PyTransform dll if remote OS architecture is 32-bit
  win_copy:
    src: '{{LOCAL_DATA_DIR}}/32Bitdll/'
    dest: '{{BOT_INSTALL_DIR}}'
    remote_src: False
    when: ansible_architecture == "32-bit"
    register: dll_replaced



- name: Copy run script to remote machines
  win_copy:
   src: '{{LOCAL_DATA_DIR}}/run.bat'
   dest: C:\bot\
   remote_src: no

- name: Copy act script to remote machines
  win_copy:
   src: '{{LOCAL_DATA_DIR}}/act.bat'
   dest: C:\bot\
   remote_src: no