---
- name: Check if run script exists on remote machine 
  win_stat:
   path: C:\bot\run.bat
  register: run_batch_script


- name: Add run script to windows startup (for Autostart)
  win_copy: 
    src: C:\bot\act.bat
    dest: '{{WIN_STARTUP_PATH}}\act.bat'
    remote_src: yes


#- name: run the batch Script on remote machines
#  win_shell: C:\bot\act.bat
#  # args:
#  #     chdir: C:\bot\
#  async: 180
#  poll: 0
#  when: run_batch_script.stat.exists
#  register: script_res
#
#- debug:
#    var: script_res

