---
- name: Install Chocolatey package manager for Windows
  win_chocolatey:
    name:
    - chocolatey
    - chocolatey-core.extension
    state: present

- name: Ensure chocolatey path is registered
  win_path:
    name: PATH
    elements: C:\ProgramData\chocolatey\bin
    scope: machine
    state: present

- name: Install git using chocolatey
  win_chocolatey:
    name: git
    state: present

- name: Install chrome using chocolatey
  win_chocolatey:
    name: googlechrome
    state: present


- name: display path after git install
  win_shell:  Write-Output $env:PATH
  register: path_after_git
  
- name: Install Anacaonda using chocolatey
  win_chocolatey:
    name: anaconda3
    state: present

- name: Ensure that Conda is added to PATH 
  win_path:
    elements: 
      - '{{ANACONDA_INSTALL_DIR}}\'
      - '{{ANACONDA_INSTALL_DIR}}\Scripts\'
      - '{{ANACONDA_INSTALL_DIR}}\Library\bin'
    scope: user
    state: present

- name: Initialize conda for powershell and cmd
  win_command: conda init {{ item }}
  args:
    chdir: '{{ANACONDA_INSTALL_DIR}}\Scripts\'
  with_items:
    - powershell 
    - cmd.exe
  register: conda_cmd_powershell

- name: install pip packages
  win_command: '{{ANACONDA_INSTALL_DIR}}\Scripts\pip install --upgrade --user {{ item }}'
  with_items:
  - vosk
  - soundfile
  - sounddevice
  - selenium
  - pipwin
  - nltk
  # become: "{{ anaconda_sudo }}"

- name: install using conda packages
  win_command: 'conda install {{ item }}'
  with_items:
  - pyaudio
  # become: "{{ anaconda_sudo }}"
